### ISSUE TITLE
rcanvas and brush

### ISSUE THREAD

**Issue by tormodb** [vusaverse/vvcanvas#1]
Hi, great that there is a new project on connecting to canvas from R. I have previously benefitted a lot from [rcanvas](https://github.com/daranzolin/rcanvas) and [brush](https://github.com/erikpal/bRush) which are packaged that aim to do similar things as this package and just wanted to make you aware that rcanvas is looking for maintainers and perhaps there is some work there that could be benefit also to this package?

**Comment by Tomeriko96** [comment]
Dear Tormod, 

Thank you very much for reaching out!

Regarding your questions, I must admit that I wasn't familiar with the brush package before. It was  brought to my attention that rcanvas was looking for maintainers by one of the contributors who works at my university. Additionally, this person is also part of the canvas discussion group which led to developing this package.

The rcanvas and brush packages certainly are more mature than this one, as they do have functions that can publish to canvas, instead of only retrieving information. As such, they have work that could benefit vvcanvas.

### on vvcanvas
I am in talks with the administrators of our Canvas instance regarding the possibility of obtaining additional rights. These rights would allow me to write and test methods that require greater permissions than what I currently have.

Subjectively speaking, the sole advantage that vvcanvas currently holds is its presence on CRAN. Being available on CRAN makes it more accessible to the R community, thus lowering the barrier to entry for users who may be interested in leveraging its functionality. 

If you have any further insights, suggestions, or feedback, please feel free to share them. You can also reach me directly through my work email:  t.iwan@vu.nl

Kind regards,

Tomer
